// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicemocks

import (
	"context"

	"github.com/anderson-reinaldo/go-explicAI/internal/application/service"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSummaryUseCase creates a new instance of MockSummaryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSummaryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSummaryUseCase {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSummaryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSummaryUseCase is an autogenerated mock type for the SummaryUseCase type
type MockSummaryUseCase struct {
	mock.Mock
}

type MockSummaryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSummaryUseCase) EXPECT() *MockSummaryUseCase_Expecter {
	return &MockSummaryUseCase_Expecter{mock: &_m.Mock}
}

// CreateSummaryAndTriggerAIProcess provides a mock function for the type MockSummaryUseCase
func (_mock *MockSummaryUseCase) CreateSummaryAndTriggerAIProcess(ctx context.Context, audio []byte) (*service.SummarySimpleOutput, error) {
	ret := _mock.Called(ctx, audio)

	if len(ret) == 0 {
		panic("no return value specified for CreateSummaryAndTriggerAIProcess")
	}

	var r0 *service.SummarySimpleOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*service.SummarySimpleOutput, error)); ok {
		return returnFunc(ctx, audio)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *service.SummarySimpleOutput); ok {
		r0 = returnFunc(ctx, audio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SummarySimpleOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, audio)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSummaryAndTriggerAIProcess'
type MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call struct {
	*mock.Call
}

// CreateSummaryAndTriggerAIProcess is a helper method to define mock.On call
//   - ctx context.Context
//   - audio []byte
func (_e *MockSummaryUseCase_Expecter) CreateSummaryAndTriggerAIProcess(ctx any, audio any) *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call {
	return &MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call{Call: _e.mock.On("CreateSummaryAndTriggerAIProcess", ctx, audio)}
}

func (_c *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call) Run(run func(ctx context.Context, audio []byte)) *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call) Return(summarySimpleOutput *service.SummarySimpleOutput, err error) *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call {
	_c.Call.Return(summarySimpleOutput, err)
	return _c
}

func (_c *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call) RunAndReturn(run func(ctx context.Context, audio []byte) (*service.SummarySimpleOutput, error)) *MockSummaryUseCase_CreateSummaryAndTriggerAIProcess_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSummaryByExternalID provides a mock function for the type MockSummaryUseCase
func (_mock *MockSummaryUseCase) DeleteSummaryByExternalID(ctx context.Context, externalID uuid.UUID) error {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSummaryByExternalID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSummaryUseCase_DeleteSummaryByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSummaryByExternalID'
type MockSummaryUseCase_DeleteSummaryByExternalID_Call struct {
	*mock.Call
}

// DeleteSummaryByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID uuid.UUID
func (_e *MockSummaryUseCase_Expecter) DeleteSummaryByExternalID(ctx any, externalID any) *MockSummaryUseCase_DeleteSummaryByExternalID_Call {
	return &MockSummaryUseCase_DeleteSummaryByExternalID_Call{Call: _e.mock.On("DeleteSummaryByExternalID", ctx, externalID)}
}

func (_c *MockSummaryUseCase_DeleteSummaryByExternalID_Call) Run(run func(ctx context.Context, externalID uuid.UUID)) *MockSummaryUseCase_DeleteSummaryByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSummaryUseCase_DeleteSummaryByExternalID_Call) Return(err error) *MockSummaryUseCase_DeleteSummaryByExternalID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSummaryUseCase_DeleteSummaryByExternalID_Call) RunAndReturn(run func(ctx context.Context, externalID uuid.UUID) error) *MockSummaryUseCase_DeleteSummaryByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummaryByExternalID provides a mock function for the type MockSummaryUseCase
func (_mock *MockSummaryUseCase) GetSummaryByExternalID(ctx context.Context, externalID uuid.UUID) (*service.SummaryDetailedOutput, error) {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryByExternalID")
	}

	var r0 *service.SummaryDetailedOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*service.SummaryDetailedOutput, error)); ok {
		return returnFunc(ctx, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *service.SummaryDetailedOutput); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SummaryDetailedOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummaryUseCase_GetSummaryByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummaryByExternalID'
type MockSummaryUseCase_GetSummaryByExternalID_Call struct {
	*mock.Call
}

// GetSummaryByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID uuid.UUID
func (_e *MockSummaryUseCase_Expecter) GetSummaryByExternalID(ctx any, externalID any) *MockSummaryUseCase_GetSummaryByExternalID_Call {
	return &MockSummaryUseCase_GetSummaryByExternalID_Call{Call: _e.mock.On("GetSummaryByExternalID", ctx, externalID)}
}

func (_c *MockSummaryUseCase_GetSummaryByExternalID_Call) Run(run func(ctx context.Context, externalID uuid.UUID)) *MockSummaryUseCase_GetSummaryByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSummaryUseCase_GetSummaryByExternalID_Call) Return(summaryDetailedOutput *service.SummaryDetailedOutput, err error) *MockSummaryUseCase_GetSummaryByExternalID_Call {
	_c.Call.Return(summaryDetailedOutput, err)
	return _c
}

func (_c *MockSummaryUseCase_GetSummaryByExternalID_Call) RunAndReturn(run func(ctx context.Context, externalID uuid.UUID) (*service.SummaryDetailedOutput, error)) *MockSummaryUseCase_GetSummaryByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// ListSummaries provides a mock function for the type MockSummaryUseCase
func (_mock *MockSummaryUseCase) ListSummaries(ctx context.Context) (*service.SummaryListOutput, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSummaries")
	}

	var r0 *service.SummaryListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*service.SummaryListOutput, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *service.SummaryListOutput); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SummaryListOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummaryUseCase_ListSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSummaries'
type MockSummaryUseCase_ListSummaries_Call struct {
	*mock.Call
}

// ListSummaries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSummaryUseCase_Expecter) ListSummaries(ctx any) *MockSummaryUseCase_ListSummaries_Call {
	return &MockSummaryUseCase_ListSummaries_Call{Call: _e.mock.On("ListSummaries", ctx)}
}

func (_c *MockSummaryUseCase_ListSummaries_Call) Run(run func(ctx context.Context)) *MockSummaryUseCase_ListSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSummaryUseCase_ListSummaries_Call) Return(summaryListOutput *service.SummaryListOutput, err error) *MockSummaryUseCase_ListSummaries_Call {
	_c.Call.Return(summaryListOutput, err)
	return _c
}

func (_c *MockSummaryUseCase_ListSummaries_Call) RunAndReturn(run func(ctx context.Context) (*service.SummaryListOutput, error)) *MockSummaryUseCase_ListSummaries_Call {
	_c.Call.Return(run)
	return _c
}
