// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gatewaymocks

import (
	"context"

	"github.com/anderson-reinaldo/go-explicAI/internal/gateway/repository"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReposistory creates a new instance of MockReposistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReposistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReposistory {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockReposistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockReposistory is an autogenerated mock type for the Reposistory type
type MockReposistory struct {
	mock.Mock
}

type MockReposistory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReposistory) EXPECT() *MockReposistory_Expecter {
	return &MockReposistory_Expecter{mock: &_m.Mock}
}

// CreateSummary provides a mock function for the type MockReposistory
func (_mock *MockReposistory) CreateSummary(ctx context.Context, status repository.Status) (*repository.SummaryCreateOutput, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CreateSummary")
	}

	var r0 *repository.SummaryCreateOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Status) (*repository.SummaryCreateOutput, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Status) *repository.SummaryCreateOutput); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.SummaryCreateOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Status) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReposistory_CreateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSummary'
type MockReposistory_CreateSummary_Call struct {
	*mock.Call
}

// CreateSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - status repository.Status
func (_e *MockReposistory_Expecter) CreateSummary(ctx any, status any) *MockReposistory_CreateSummary_Call {
	return &MockReposistory_CreateSummary_Call{Call: _e.mock.On("CreateSummary", ctx, status)}
}

func (_c *MockReposistory_CreateSummary_Call) Run(run func(ctx context.Context, status repository.Status)) *MockReposistory_CreateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Status
		if args[1] != nil {
			arg1 = args[1].(repository.Status)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReposistory_CreateSummary_Call) Return(summaryCreateOutput *repository.SummaryCreateOutput, err error) *MockReposistory_CreateSummary_Call {
	_c.Call.Return(summaryCreateOutput, err)
	return _c
}

func (_c *MockReposistory_CreateSummary_Call) RunAndReturn(run func(ctx context.Context, status repository.Status) (*repository.SummaryCreateOutput, error)) *MockReposistory_CreateSummary_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSummaryByExternalID provides a mock function for the type MockReposistory
func (_mock *MockReposistory) DeleteSummaryByExternalID(ctx context.Context, externalID uuid.UUID) error {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSummaryByExternalID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReposistory_DeleteSummaryByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSummaryByExternalID'
type MockReposistory_DeleteSummaryByExternalID_Call struct {
	*mock.Call
}

// DeleteSummaryByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID uuid.UUID
func (_e *MockReposistory_Expecter) DeleteSummaryByExternalID(ctx any, externalID any) *MockReposistory_DeleteSummaryByExternalID_Call {
	return &MockReposistory_DeleteSummaryByExternalID_Call{Call: _e.mock.On("DeleteSummaryByExternalID", ctx, externalID)}
}

func (_c *MockReposistory_DeleteSummaryByExternalID_Call) Run(run func(ctx context.Context, externalID uuid.UUID)) *MockReposistory_DeleteSummaryByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReposistory_DeleteSummaryByExternalID_Call) Return(err error) *MockReposistory_DeleteSummaryByExternalID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReposistory_DeleteSummaryByExternalID_Call) RunAndReturn(run func(ctx context.Context, externalID uuid.UUID) error) *MockReposistory_DeleteSummaryByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummaries provides a mock function for the type MockReposistory
func (_mock *MockReposistory) GetSummaries(ctx context.Context) ([]repository.SummaryOutput, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaries")
	}

	var r0 []repository.SummaryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.SummaryOutput, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.SummaryOutput); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SummaryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReposistory_GetSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummaries'
type MockReposistory_GetSummaries_Call struct {
	*mock.Call
}

// GetSummaries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReposistory_Expecter) GetSummaries(ctx any) *MockReposistory_GetSummaries_Call {
	return &MockReposistory_GetSummaries_Call{Call: _e.mock.On("GetSummaries", ctx)}
}

func (_c *MockReposistory_GetSummaries_Call) Run(run func(ctx context.Context)) *MockReposistory_GetSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReposistory_GetSummaries_Call) Return(summaryOutputs []repository.SummaryOutput, err error) *MockReposistory_GetSummaries_Call {
	_c.Call.Return(summaryOutputs, err)
	return _c
}

func (_c *MockReposistory_GetSummaries_Call) RunAndReturn(run func(ctx context.Context) ([]repository.SummaryOutput, error)) *MockReposistory_GetSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummaryByExternalID provides a mock function for the type MockReposistory
func (_mock *MockReposistory) GetSummaryByExternalID(ctx context.Context, externalID uuid.UUID) (*repository.SummaryOutput, error) {
	ret := _mock.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetSummaryByExternalID")
	}

	var r0 *repository.SummaryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*repository.SummaryOutput, error)); ok {
		return returnFunc(ctx, externalID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *repository.SummaryOutput); ok {
		r0 = returnFunc(ctx, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.SummaryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReposistory_GetSummaryByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummaryByExternalID'
type MockReposistory_GetSummaryByExternalID_Call struct {
	*mock.Call
}

// GetSummaryByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID uuid.UUID
func (_e *MockReposistory_Expecter) GetSummaryByExternalID(ctx any, externalID any) *MockReposistory_GetSummaryByExternalID_Call {
	return &MockReposistory_GetSummaryByExternalID_Call{Call: _e.mock.On("GetSummaryByExternalID", ctx, externalID)}
}

func (_c *MockReposistory_GetSummaryByExternalID_Call) Run(run func(ctx context.Context, externalID uuid.UUID)) *MockReposistory_GetSummaryByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReposistory_GetSummaryByExternalID_Call) Return(summaryOutput *repository.SummaryOutput, err error) *MockReposistory_GetSummaryByExternalID_Call {
	_c.Call.Return(summaryOutput, err)
	return _c
}

func (_c *MockReposistory_GetSummaryByExternalID_Call) RunAndReturn(run func(ctx context.Context, externalID uuid.UUID) (*repository.SummaryOutput, error)) *MockReposistory_GetSummaryByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSummarySummarized provides a mock function for the type MockReposistory
func (_mock *MockReposistory) UpdateSummarySummarized(ctx context.Context, input repository.SummaryUpdateSummarizedInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSummarySummarized")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SummaryUpdateSummarizedInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReposistory_UpdateSummarySummarized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSummarySummarized'
type MockReposistory_UpdateSummarySummarized_Call struct {
	*mock.Call
}

// UpdateSummarySummarized is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.SummaryUpdateSummarizedInput
func (_e *MockReposistory_Expecter) UpdateSummarySummarized(ctx any, input any) *MockReposistory_UpdateSummarySummarized_Call {
	return &MockReposistory_UpdateSummarySummarized_Call{Call: _e.mock.On("UpdateSummarySummarized", ctx, input)}
}

func (_c *MockReposistory_UpdateSummarySummarized_Call) Run(run func(ctx context.Context, input repository.SummaryUpdateSummarizedInput)) *MockReposistory_UpdateSummarySummarized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SummaryUpdateSummarizedInput
		if args[1] != nil {
			arg1 = args[1].(repository.SummaryUpdateSummarizedInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReposistory_UpdateSummarySummarized_Call) Return(err error) *MockReposistory_UpdateSummarySummarized_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReposistory_UpdateSummarySummarized_Call) RunAndReturn(run func(ctx context.Context, input repository.SummaryUpdateSummarizedInput) error) *MockReposistory_UpdateSummarySummarized_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSummaryTranscribed provides a mock function for the type MockReposistory
func (_mock *MockReposistory) UpdateSummaryTranscribed(ctx context.Context, input repository.SummaryUpdateTranscribedInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSummaryTranscribed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SummaryUpdateTranscribedInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReposistory_UpdateSummaryTranscribed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSummaryTranscribed'
type MockReposistory_UpdateSummaryTranscribed_Call struct {
	*mock.Call
}

// UpdateSummaryTranscribed is a helper method to define mock.On call
//   - ctx context.Context
//   - input repository.SummaryUpdateTranscribedInput
func (_e *MockReposistory_Expecter) UpdateSummaryTranscribed(ctx any, input any) *MockReposistory_UpdateSummaryTranscribed_Call {
	return &MockReposistory_UpdateSummaryTranscribed_Call{Call: _e.mock.On("UpdateSummaryTranscribed", ctx, input)}
}

func (_c *MockReposistory_UpdateSummaryTranscribed_Call) Run(run func(ctx context.Context, input repository.SummaryUpdateTranscribedInput)) *MockReposistory_UpdateSummaryTranscribed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SummaryUpdateTranscribedInput
		if args[1] != nil {
			arg1 = args[1].(repository.SummaryUpdateTranscribedInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReposistory_UpdateSummaryTranscribed_Call) Return(err error) *MockReposistory_UpdateSummaryTranscribed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReposistory_UpdateSummaryTranscribed_Call) RunAndReturn(run func(ctx context.Context, input repository.SummaryUpdateTranscribedInput) error) *MockReposistory_UpdateSummaryTranscribed_Call {
	_c.Call.Return(run)
	return _c
}
