// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gatewaymocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAudioTranscript creates a new instance of MockAudioTranscript. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudioTranscript(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudioTranscript {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAudioTranscript{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAudioTranscript is an autogenerated mock type for the AudioTranscript type
type MockAudioTranscript struct {
	mock.Mock
}

type MockAudioTranscript_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudioTranscript) EXPECT() *MockAudioTranscript_Expecter {
	return &MockAudioTranscript_Expecter{mock: &_m.Mock}
}

// Transcribe provides a mock function for the type MockAudioTranscript
func (_mock *MockAudioTranscript) Transcribe(ctx context.Context, audio []byte) (*string, error) {
	ret := _mock.Called(ctx, audio)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (*string, error)); ok {
		return returnFunc(ctx, audio)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) *string); ok {
		r0 = returnFunc(ctx, audio)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, audio)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudioTranscript_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type MockAudioTranscript_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - ctx context.Context
//   - audio []byte
func (_e *MockAudioTranscript_Expecter) Transcribe(ctx any, audio any) *MockAudioTranscript_Transcribe_Call {
	return &MockAudioTranscript_Transcribe_Call{Call: _e.mock.On("Transcribe", ctx, audio)}
}

func (_c *MockAudioTranscript_Transcribe_Call) Run(run func(ctx context.Context, audio []byte)) *MockAudioTranscript_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudioTranscript_Transcribe_Call) Return(s *string, err error) *MockAudioTranscript_Transcribe_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAudioTranscript_Transcribe_Call) RunAndReturn(run func(ctx context.Context, audio []byte) (*string, error)) *MockAudioTranscript_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}
