// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gatewaymocks

import (
	"context"

	"github.com/anderson-reinaldo/go-explicAI/internal/gateway/summarize"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSummarize creates a new instance of MockSummarize. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSummarize(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSummarize {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSummarize{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSummarize is an autogenerated mock type for the Summarize type
type MockSummarize struct {
	mock.Mock
}

type MockSummarize_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSummarize) EXPECT() *MockSummarize_Expecter {
	return &MockSummarize_Expecter{mock: &_m.Mock}
}

// FullTextOrganize provides a mock function for the type MockSummarize
func (_mock *MockSummarize) FullTextOrganize(ctx context.Context, trascription string) (*string, error) {
	ret := _mock.Called(ctx, trascription)

	if len(ret) == 0 {
		panic("no return value specified for FullTextOrganize")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return returnFunc(ctx, trascription)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = returnFunc(ctx, trascription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, trascription)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummarize_FullTextOrganize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullTextOrganize'
type MockSummarize_FullTextOrganize_Call struct {
	*mock.Call
}

// FullTextOrganize is a helper method to define mock.On call
//   - ctx context.Context
//   - trascription string
func (_e *MockSummarize_Expecter) FullTextOrganize(ctx any, trascription any) *MockSummarize_FullTextOrganize_Call {
	return &MockSummarize_FullTextOrganize_Call{Call: _e.mock.On("FullTextOrganize", ctx, trascription)}
}

func (_c *MockSummarize_FullTextOrganize_Call) Run(run func(ctx context.Context, trascription string)) *MockSummarize_FullTextOrganize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSummarize_FullTextOrganize_Call) Return(s *string, err error) *MockSummarize_FullTextOrganize_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSummarize_FullTextOrganize_Call) RunAndReturn(run func(ctx context.Context, trascription string) (*string, error)) *MockSummarize_FullTextOrganize_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockSummarize
func (_mock *MockSummarize) Resume(ctx context.Context, transcription string) (*summarize.ResumeOutput, error) {
	ret := _mock.Called(ctx, transcription)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 *summarize.ResumeOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*summarize.ResumeOutput, error)); ok {
		return returnFunc(ctx, transcription)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *summarize.ResumeOutput); ok {
		r0 = returnFunc(ctx, transcription)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*summarize.ResumeOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, transcription)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummarize_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockSummarize_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - transcription string
func (_e *MockSummarize_Expecter) Resume(ctx any, transcription any) *MockSummarize_Resume_Call {
	return &MockSummarize_Resume_Call{Call: _e.mock.On("Resume", ctx, transcription)}
}

func (_c *MockSummarize_Resume_Call) Run(run func(ctx context.Context, transcription string)) *MockSummarize_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSummarize_Resume_Call) Return(resumeOutput *summarize.ResumeOutput, err error) *MockSummarize_Resume_Call {
	_c.Call.Return(resumeOutput, err)
	return _c
}

func (_c *MockSummarize_Resume_Call) RunAndReturn(run func(ctx context.Context, transcription string) (*summarize.ResumeOutput, error)) *MockSummarize_Resume_Call {
	_c.Call.Return(run)
	return _c
}
